name: right
description: "Right app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/imgs/
